# fly.toml app configuration file generated for oroute on 2026-03-20T09:12:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'leeomniroute'
primary_region = 'sin'

[build]
  image = 'diegosouzapw/omniroute:latest'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 20128
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true


[env]
  DATA_DIR = "/data"
  TZ = "Asia/Ho_Chi_Minh"
  HOST = "0.0.0.0"
  HOSTNAME = "0.0.0.0"
  BIND = "0.0.0.0"
  NEXT_PUBLIC_BASE_URL = "https://leeomniroute.fly.dev"
